name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npx eslint
